/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import ModeloArr.Materiales;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author M
 */
public class MaterialesAdmi extends javax.swing.JFrame {

    Materiales[] ArrMateriales;
    int IndiceBuscarMat;
    /**
     * Creates new form EmpresaAdmi
     */
    public MaterialesAdmi() {

        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Registro Materiales de Fabricacion");
        setSize(537, 392);
       try {
            setIconImage(new ImageIcon(getClass().getResource("../imagenes/notas.png")).getImage());
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDescripmat = new javax.swing.JTextField();
        comMaterialsimp = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDMaterial = new javax.swing.JTextField();
        btbBuscarMaterial = new javax.swing.JButton();
        btbGuardarMat = new javax.swing.JButton();
        BtbEliminarMat = new javax.swing.JButton();
        btbModificarMat = new javax.swing.JButton();
        bttMostrarMat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Descripcion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        getContentPane().add(txtDescripmat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 260, 40));

        comMaterialsimp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comMaterialsimp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo del material :", "Simple", "hibrido" }));
        comMaterialsimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comMaterialsimpActionPerformed(evt);
            }
        });
        getContentPane().add(comMaterialsimp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 240, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID MATERIAL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Gestionar Materiales");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("COLECCIONISTA DE BILLETES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tipo material");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 20));
        getContentPane().add(txtIDMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 220, 30));

        btbBuscarMaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btbBuscarMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busqueda.png"))); // NOI18N
        btbBuscarMaterial.setText("Buscar");
        btbBuscarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbBuscarMaterialActionPerformed(evt);
            }
        });
        getContentPane().add(btbBuscarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 110, 30));

        btbGuardarMat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btbGuardarMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btbGuardarMat.setText("Guardar");
        btbGuardarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbGuardarMatActionPerformed(evt);
            }
        });
        getContentPane().add(btbGuardarMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, 30));

        BtbEliminarMat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtbEliminarMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/basura.png"))); // NOI18N
        BtbEliminarMat.setText("Eliminar");
        BtbEliminarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtbEliminarMatActionPerformed(evt);
            }
        });
        getContentPane().add(BtbEliminarMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 120, 30));

        btbModificarMat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btbModificarMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btbModificarMat.setText("Modificar");
        btbModificarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbModificarMatActionPerformed(evt);
            }
        });
        getContentPane().add(btbModificarMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, 30));

        bttMostrarMat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttMostrarMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/binoculares.png"))); // NOI18N
        bttMostrarMat.setText("MOSTRAR");
        bttMostrarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttMostrarMatActionPerformed(evt);
            }
        });
        getContentPane().add(bttMostrarMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comMaterialsimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comMaterialsimpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comMaterialsimpActionPerformed

    private void btbGuardarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbGuardarMatActionPerformed
        Materiales mate = new Materiales();
        mate.setNombreMaterial(this.comMaterialsimp.getSelectedItem().toString());
        if (!this.txtDescripmat.toString().equals("")) {
            mate.setDescripcion(this.txtDescripmat.getText());
            mate.setID(Integer.parseInt(this.txtIDMaterial.getText()));
            MenuAdmin.Arrmateriales.insertarMaterial(mate);
            JOptionPane.showMessageDialog(null, "Material insertado");
            this.txtDescripmat.setText("");
            this.comMaterialsimp.setSelectedIndex(0);
            this.txtIDMaterial.setText("");
        }
    }//GEN-LAST:event_btbGuardarMatActionPerformed

 
    private void BtbEliminarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtbEliminarMatActionPerformed
        String[] NomFab = new String[MenuAdmin.Arrmateriales.posAct];

        int i = 0;
        while (i < NomFab.length) {
            NomFab[i] = (MenuAdmin.Arrmateriales.getArrMateriales()[i].getDescripcion());
            i++;
        }

        int pos = JOptionPane.showOptionDialog(
                null, "Seleccione el material a eliminar",
                "eliminar material",
                JOptionPane.DEFAULT_OPTION, JOptionPane.NO_OPTION, null, NomFab, NomFab[0]);

        MenuAdmin.Arrmateriales.eliminarMat(pos);

        //fin eliminar mateiral
    }//GEN-LAST:event_BtbEliminarMatActionPerformed
public void buscarmaterial(){
 String stringIdBuscar = JOptionPane.showInputDialog("DIGITE EL ID DE LA EMPRESA","ID");
        if (stringIdBuscar != null && !"".equals(stringIdBuscar)) {
            int codBuscar = Integer.parseInt(stringIdBuscar);
            boolean buscar = false;
            for (int i = 0; i < MenuAdmin.Arrmateriales.posAct; i++) {
                if (MenuAdmin.Arrmateriales.getArrMateriales()[i].getID()== codBuscar) {
                    IndiceBuscarMat = i;
                    JOptionPane.showMessageDialog(null, "Si existe");
                    
                    buscar = true;
                    
                } else {
                    if (!buscar) {
                        JOptionPane.showMessageDialog(this, "El material no existe", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                
            
                }
            }
        }
}


    private void btbBuscarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbBuscarMaterialActionPerformed
    buscarmaterial();


    }//GEN-LAST:event_btbBuscarMaterialActionPerformed

    private void bttMostrarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttMostrarMatActionPerformed
 ;
        JOptionPane.showMessageDialog(null, MenuAdmin.Arrmateriales.listarMateriales());
        
//        txtDescripmat.setVisible(false);
//        BtbEliminarMat.setVisible(false);
//        btbModificarMat.setVisible(false);
//       txtIDMaterial.setVisible(false);
//       btbBuscarMaterial.setVisible(false);
//       btbGuardarMat.setVisible(false);
//       bttMostrarMat.setVisible(false);
//       comMaterialsimp.setVisible(false);
//       jLabel2.setVisible(false);
//       jLabel1.setVisible(false);
//      jLabel3.setVisible(false);
//      jLabel4.setVisible(false);
//      jLabel5.setVisible(false);
////      MenuAdmin.Arrmateriales.
//                 this.panelprueba.addChangeListener(new ChangeListener() {
//            @Override
//            public void stateChanged(ChangeEvent e) {
//                if (e.getSource() instanceof JTabbedPane) {
//                    JTabbedPane pane = (JTabbedPane) e.getSource();
//                    if (pane.getSelectedIndex() == 1) { //solo cuando le de en el tab de buscar
//                        //listar matariales
//                        PRUEBALISTA.setText(MenuAdmin.Arrmateriales.listarMateriales());
//                    }
//                }
//            }
//        });

        
            
               
    }//GEN-LAST:event_bttMostrarMatActionPerformed

    private void btbModificarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbModificarMatActionPerformed
       ModificarMaterial ModMaterial = new ModificarMaterial();
       ModMaterial.setVisible(true);
    }//GEN-LAST:event_btbModificarMatActionPerformed
 
 

   

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaterialesAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaterialesAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaterialesAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaterialesAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaterialesAdmi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtbEliminarMat;
    private javax.swing.JButton btbBuscarMaterial;
    private javax.swing.JButton btbGuardarMat;
    private javax.swing.JButton btbModificarMat;
    private javax.swing.JButton bttMostrarMat;
    private javax.swing.JComboBox<String> comMaterialsimp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDescripmat;
    private javax.swing.JTextField txtIDMaterial;
    // End of variables declaration//GEN-END:variables
}
