/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import ModeloArr.Materiales;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author M
 */
public class ModificarMaterial extends javax.swing.JFrame {

 
    public ModificarMaterial() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Modificar Materiales");
        setSize(465, 336);
        this.cargamat();
         try {
            setIconImage(new ImageIcon(getClass().getResource("../imagenes/notas.png")).getImage());
        } catch (Exception ex) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colemdo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbCodigoNuevoMat = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmTipoMatNuevo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDescrNuevo = new javax.swing.JTextField();
        BTBModificarMaterial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        colemdo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        colemdo.setText("COLECCIONISTA DE BILLETES");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Modificar Material");

        cbCodigoNuevoMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo A modificar:" }));
        cbCodigoNuevoMat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCodigoNuevoMatItemStateChanged(evt);
            }
        });
        cbCodigoNuevoMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCodigoNuevoMatMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tipo Material");

        cmTipoMatNuevo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Hibrido" }));
        cmTipoMatNuevo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmTipoMatNuevoFocusGained(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Descripcion");

        BTBModificarMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        BTBModificarMaterial.setText("Modificar");
        BTBModificarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBModificarMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTBModificarMaterial)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDescrNuevo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmTipoMatNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbCodigoNuevoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(colemdo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel3)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colemdo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCodigoNuevoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmTipoMatNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescrNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTBModificarMaterial)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTBModificarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBModificarMaterialActionPerformed
        int indiceMaterial = MenuAdmin.Arrmateriales.getIndexMat(
                Integer.parseInt(cbCodigoNuevoMat.getItemAt(cbCodigoNuevoMat.getSelectedIndex())));

        Materiales materialEdit = MenuAdmin.Arrmateriales.getArrMateriales()[indiceMaterial];
        //modificar atributos por los nuevos

        //capturar valores y hacer las validaciones
        String descr = txtDescrNuevo.getText();
       
      

        //asignar nuevos valores al objeto
        materialEdit.setDescripcion(descr);
        materialEdit.setNombreMaterial(this.cmTipoMatNuevo.getSelectedItem().toString());
       

        //modifico el array para que quede editado
        MenuAdmin.Arrmateriales.getArrMateriales()[indiceMaterial] = materialEdit;
        JOptionPane.showMessageDialog(null, "modificacion exitosa");
    }//GEN-LAST:event_BTBModificarMaterialActionPerformed

    private void cmTipoMatNuevoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmTipoMatNuevoFocusGained


    }//GEN-LAST:event_cmTipoMatNuevoFocusGained

    private void cbCodigoNuevoMatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCodigoNuevoMatItemStateChanged
     
    }//GEN-LAST:event_cbCodigoNuevoMatItemStateChanged

    private void cbCodigoNuevoMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCodigoNuevoMatMouseClicked
    String elemento = cbCodigoNuevoMat.getItemAt(cbCodigoNuevoMat.getSelectedIndex());
        if (elemento.indexOf("Seleccione")!= -1) {
            return;
        }

        //cargar los datos del formulario
        Materiales materiales = MenuAdmin.Arrmateriales.buscarmaterial(Integer.parseInt(elemento));
  
        txtDescrNuevo.setText("" + materiales.getDescripcion());
//       cmTipoMatNuevo.getItemAt(Integer.parseInt(materiales.getNombreMaterial()));   
        cmTipoMatNuevo.setSelectedItem(materiales.getNombreMaterial());           // TODO add your handling code here:
    }//GEN-LAST:event_cbCodigoNuevoMatMouseClicked

    private void cargamat() {
     cbCodigoNuevoMat.removeAllItems();
        int i = 0;
        cbCodigoNuevoMat.addItem("Seleccione un codigo de la lista");
        while (i < MenuAdmin.Arrmateriales.getPosAct()) {
            cbCodigoNuevoMat.addItem("" + MenuAdmin.Arrmateriales.getArrMateriales()[i].getID());
            i++;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTBModificarMaterial;
    private javax.swing.JComboBox<String> cbCodigoNuevoMat;
    private javax.swing.JComboBox<String> cmTipoMatNuevo;
    private javax.swing.JLabel colemdo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDescrNuevo;
    // End of variables declaration//GEN-END:variables
}
