/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import ModeloArr.Empresa;
import ModeloArr.Pais;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author M
 */
public class ModificarEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form ModificarEmpresa
     */
    public ModificarEmpresa() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Modificar Materiales");
        setSize(404, 362);
        this.cargarCodigoEmpresa();
         try {
            setIconImage(new ImageIcon(getClass().getResource("../imagenes/notas.png")).getImage());
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        colemdo1 = new javax.swing.JLabel();
        jLabelid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        ModificarEmpresabtb = new javax.swing.JButton();
        cmbIDEmpresa = new javax.swing.JComboBox<>();
        cmbPaisEmpresaNuevo = new javax.swing.JComboBox<>();
        txtNombreEmpresaNuevo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Modificar Empresa");

        colemdo1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        colemdo1.setText("COLECCIONISTA DE BILLETES");

        jLabelid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelid.setText("ID Empresa");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Pais Empresa");

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel.setText("Nombre Empresa");

        ModificarEmpresabtb.setText("Modificar");
        ModificarEmpresabtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarEmpresabtbActionPerformed(evt);
            }
        });

        cmbIDEmpresa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbIDEmpresaItemStateChanged(evt);
            }
        });

        cmbPaisEmpresaNuevo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbPaisEmpresaNuevoFocusGained(evt);
            }
        });

        txtNombreEmpresaNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmpresaNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreEmpresaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(cmbPaisEmpresaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ModificarEmpresabtb)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelid)
                        .addGap(55, 55, 55)
                        .addComponent(cmbIDEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(colemdo1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(colemdo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelid)
                    .addComponent(cmbIDEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel)
                    .addComponent(txtNombreEmpresaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPaisEmpresaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(ModificarEmpresabtb)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarEmpresabtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarEmpresabtbActionPerformed
        int indiceEmpresa = MenuAdmin.ArrEmpresa.getIndexEmp(
                Integer.parseInt(cmbIDEmpresa.getItemAt(cmbIDEmpresa.getSelectedIndex())));

        Empresa Emp = MenuAdmin.ArrEmpresa.getArrEmp()[indiceEmpresa];
        //modificar atributos por los nuevos

        //capturar valores y hacer las validaciones
        String nombree = txtNombreEmpresaNuevo.getText();
        Pais pais = new Pais();
        int IndicePais = cmbPaisEmpresaNuevo.getSelectedIndex();
        String Pais = cmbPaisEmpresaNuevo.getItemAt(IndicePais);
        pais.setPais(Pais);

        //asignar nuevos valores al objeto
        Emp.setNombreEmpresa(nombree);
        Emp.setPaisEmpresa(pais);

        //modifico el array para que quede editado
        MenuAdmin.ArrEmpresa.getArrEmp()[indiceEmpresa] = Emp;
        JOptionPane.showMessageDialog(null, "Modificacion Exitosa");


    }//GEN-LAST:event_ModificarEmpresabtbActionPerformed

    private void txtNombreEmpresaNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmpresaNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEmpresaNuevoActionPerformed

    private void cmbPaisEmpresaNuevoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbPaisEmpresaNuevoFocusGained
        cmbPaisEmpresaNuevo.removeAllItems();
        int i = 0;
        while (i < MenuAdmin.Arrpais.getPosAct()) {
            cmbPaisEmpresaNuevo.addItem(MenuAdmin.Arrpais.getArrPais()[i].getPais());
            i++;

        }
    }//GEN-LAST:event_cmbPaisEmpresaNuevoFocusGained

    private void cmbIDEmpresaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbIDEmpresaItemStateChanged
        String elemento = cmbIDEmpresa.getItemAt(cmbIDEmpresa.getSelectedIndex());
        if (elemento.indexOf("Seleccione") != -1) {
            return;
        }

        //cargar los datos del formulario
        Empresa empresas = MenuAdmin.ArrEmpresa.busModEmpresa(Integer.parseInt(elemento));
        txtNombreEmpresaNuevo.setText("" + empresas.getNombreEmpresa());        // TODO add your handling code here:
    }//GEN-LAST:event_cmbIDEmpresaItemStateChanged

    /**
     * @param args the command line arguments
     */
    private void cargarCodigoEmpresa() {
        cmbIDEmpresa.removeAllItems();
        int i = 0;
        cmbIDEmpresa.addItem("Seleccione un codigo de la lista");
        while (i < MenuAdmin.ArrEmpresa.getPosAct()) {
            cmbIDEmpresa.addItem("" + MenuAdmin.ArrEmpresa.getArrEmp()[i].getIDEmpresa());
            i++;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ModificarEmpresabtb;
    private javax.swing.JComboBox<String> cmbIDEmpresa;
    private javax.swing.JComboBox<String> cmbPaisEmpresaNuevo;
    private javax.swing.JLabel colemdo1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JTextField txtNombreEmpresaNuevo;
    // End of variables declaration//GEN-END:variables
}
